#!/bin/bash
#SBATCH -N 1
#SBATCH -n 32
#SBATCH -J VASP-dtk
#SBATCH --gres=dcu:4
#SBATCH -p kshdnormal

module purge
source /public/home/yangtao520/apprepo/vasp/6-dtk/scripts/env.sh

#指定版本,std,gam或ncl版
VASP_EXE=vasp_std

config=config.${SLURM_JOB_ID}
echo -e "-genv OMP_NUM_THREADS 6 \c" > $config
for i in $(scontrol show hostnames $SLURM_NODELIST)
do
  for ((j=0; j<4; j++))
  do
    echo "-host $i -env HIP_VISIBLE_DEVICES $j -n 1 numactl --cpunodebind=$j --membind=$j $VASP_EXE" >> $config
  done
done

ulimit -s unlimited

export NCCL_IB_HCA="mlx5_0"
export HSA_FORCE_FINE_GRAIN_PCIE=1

mpirun -configfile $config
